[comment {--- Standard section about retrieval from fossil --}]

Assuming that you simply wish to look at the sources of the project,
or build a specific revision, the easiest way of retrieving the
sources is to:

[list_begin enum]

[enum] Log as "anonymous" into the repository (see [sectref Location]).
       Use the semi-random password in the captcha.

[enum] Go to the "Timeline".

[enum] Choose the revision you wish to have and 

[enum] follow its link to its detailed information page.

[enum] On that page, choose either the "ZIP" or "Tarball" link to get
a copy of this revision in the format of your choice.

[list_end]
