[comment {--- !doctools ---}]
[comment { option :: --html-dir :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --html-dir path]

This configuration option specifies the path to the directory package
documentation in HTML format will be installed into.

[para] The default value is [file [var --prefix]/html].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
