[comment {--- !doctools ---}]
[comment { option :: --prefix :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --prefix path]

This configuration option specifies the path to the root directory for
all platform-independent (non-binary) installation files.

[para] The default value is the twice parent of the
[lb][cmd {info library}][rb] directory of the [syscmd tclsh] used to
run the [syscmd kettle] application.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
