[comment {--- !doctools ---}]
[comment { option :: --target :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --target string]

The value of this option is the target name [syscmd critcl] should use
to build C code.

[para] The default value is the empty string, leaving the choice of
target to [syscmd critcl] itself.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
