[comment {--- !doctools ---}]
[comment { option :: --verbose :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --verbose boolean]

The value of this configuration option determines if tracing of system
internals is done ([const on]), or not ([const off]). This is the
option equivalent of the special flag [option -trace].

[para] The default value is [const off], disabling tracing of internals.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
