[comment {--- !doctools ---}]
[comment { option :: --with-dtplite :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --with-dtplite path]

This configuration option specifies the path to the tool
[syscmd dtplite] for doctools-based documentation processing.

[para]	The default value is the path to the first of
	[file dtplite],
	[file dtplite.kit],
	[file dtplite.tcl], and
	[file dtplite.exe]

found on the [var PATH].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
