[subsection {Changes for version 2}]

This is the second release of kettle, package and application.

[para] In detail:

[list_begin enumerated]
[comment {- - -- --- ----- -------- ------------- ---------------------}]
[enum]	The DSL was backward compatibly extended to support two new
	commands managing a list of glob patterns. Files matching
	at least one of the patterns are ignored when scanning the
	project directory. The standard set of patterns ignores core
	files.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[list_end]
