[comment {-*- tcl -*- --- !doctools --- manpage}]
[comment {- - -- --- ----- -------- ------------- ---------------------}]
[section {Bugs, Ideas, Feedback}]
[vset R https://chiselapp.com/user/andreas_kupries/repository/Kettle/index]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at the
[uri [vset R] {Kettle Tracker}].

Please also report any ideas for enhancements you may have for either
package and/or documentation.

