[comment {--- !doctools ---}]
[comment { support :: kettle ovalidate :: }]

This layer defines the validation types usable by the options.

[list_begin definitions]
[call [cmd {kettle ovalidate}] [method enum]]
[call [cmd {kettle ovalidate}] [method any]]
[call [cmd {kettle ovalidate}] [method string]]
[call [cmd {kettle ovalidate}] [method boolean]]
[call [cmd {kettle ovalidate}] [method listsimple]]
[call [cmd {kettle ovalidate}] [method directory]]
[call [cmd {kettle ovalidate}] [method readable.file]]
[call [cmd {kettle ovalidate}] [method path]]
[list_end]
