[comment {--- !doctools ---}]
[comment { support :: kettle recipe :: }]

This layer contains the commands managing the database of all known
recipes, ready for execution.

[list_begin definitions]
[call [cmd {kettle recipe}] [method define]]
[call [cmd {kettle recipe}] [method parent]]
[call [cmd {kettle recipe}] [method exists]]
[call [cmd {kettle recipe}] [method names]]
[call [cmd {kettle recipe}] [method help]]
[call [cmd {kettle recipe}] [method run]]
[list_end]
