[comment {--- !doctools ---}]
[comment { option :: --dry :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --dry boolean]

The value of this configuration option determines if (un)installation
modifies the file system ([const off]) or not ([const on] == dry run).

[para] The default value is [const off]. This means that the system
will modify the file system as instructed by recipes.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
