[comment {--- !doctools ---}]
[comment { option :: --exec-prefix :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --exec-prefix path]

This configuration option specifies the path to the root directory for
all platform-dependent (binary) installation files.

[para] The default value is [file [var --prefix]].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
