[comment {--- !doctools ---}]
[comment { option :: --log :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --log path]


An option for recipe 'test', if defined. Its value is the path "stem"
for a series of files testsuite information is saved into. The actual
files use the specified stem and add their specifc file extension to
it.

[para] The default is the empty string, disabling the saving of
testsuite information.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
