[comment {--- !doctools ---}]
[comment { option :: --log-mode :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --log-mode compact|full]

An option for recipe 'test', if defined. Its value determines the
verbosity of test suite information printed to the terminal or log window.

[para] The default is [const compact].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
