[comment {--- !doctools ---}]
[comment { option :: --man-dir :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --man-dir path]

This configuration option specifies the path to the directory package
documentation (manpages, in *roff format) will be installed into.

[para] The default value is [file [var --prefix]/man].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
