[comment {--- !doctools ---}]
[comment { option :: --with-dia :: }]

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[opt_def --with-dia path]

This configuration option specifies the path to the tool
[syscmd dia] for tklib/diagram-based diagram processing.

[para]	The default value is the path to the first of
	[file dia],
	[file dia.kit],
	[file dia.tcl], and
	[file dia.exe]

found on the [var PATH].

[comment {- - -- --- ----- -------- ------------- ---------------------}]
