[subsection Kettle]

This project uses the Kettle application and package as its build system.

[para] Please go to either the main repository at
[uri http://core.tcl.tk/akupries/kettle]

or the backup at
[uri http://chiselapp.com/andreas_kupries/repositories/Kettle]

and follow the instructions given at these sites to create a working
installation. They are not repeated here. If there are problems with
these instructions please file a bug against the Kettle project, and
not [vset PTITLE].

[para]
